# --- JOB 2 : DÉPLOIEMENT ---
  deploy-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: "Clonage du code source"
        uses: actions/checkout@v4

      - name: "Installation des binaires SOPS et Age"
        run: |
          sudo apt-get update && sudo apt-get install -y age
          curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          sudo mv sops-v3.8.1.linux.amd64 /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops

      - name: "Installation des modules Node.js"
        run: npm ci

      - name: "Déchiffrement et Lancement hermétique de l'application"
        # On passe la clé secrète en variable d'environnement pour SOPS
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          echo "🚀 Extraction des secrets de production au format dotenv..."
          
          # SOPS déchiffre et convertit le YAML en paires CLE=VALEUR dans un fichier masqué
          sops -d --output-type dotenv secrets-prod.yaml > .env.production
          
          # Chargement des variables en mémoire sans les afficher
          export $(cat .env.production | xargs)
          
          echo "Démarrage de l'application..."
          node src/server.js &
          
          # Simulation d'un contrôle de santé du serveur
          sleep 3
          echo "✅ Serveur démarré en production avec les bons secrets."
          
          # Principe de SoD / Zero Trust : on détruit les traces immédiatement
          rm .env.production
          echo "🧹 Traces nettoyées."
